#!/usr/bin/env python

import sys
import os

if len(sys.argv) < 2:
  print("Please input Gromacs version")
  exit(1)

versions_file = os.getenv("HOME") + "/.gromacs_versions"

versions = {}

with open(versions_file,'r') as f:
  for line in f:
    doc = line.strip().split(',')
    version = doc[0]
    path = doc[1]
    versions[version] = path

try:
  print(versions[sys.argv[1]])
except KeyError:
  print("Gromacs {0} path not found".format(sys.argv[1]))
  exit(1)
